env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
rules:
  max-len: ["error", { "code": 78, "ignoreUrls": true }]
  max-lines: ["error", { "max": 140, "skipComments": true, "skipBlankLines": true }]
  max-lines-per-function: ["error", { "max": 40, "skipComments": true, "skipBlankLines": true }]
  no-use-before-define: ["error", { "functions": false }]
  prettier/prettier: "error"
  no-console: "off"
