env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
rules:
  max-lines: ["error", {"max": 200, "skipComments": true, "skipBlankLines": true}]
  max-lines-per-function: ["error", {"max": 80, "skipComments": true, "skipBlankLines": true}]
  max-len: ["error", {"code": 80, "ignoreUrls": true}]
  prettier/prettier: "error"
  no-console: "off"
